m_db/urls.py
from django.conf.urls import url
from .views import set_password, user_login, user_logout, index


urlpatterns = [
    url(r'^set-password/(?P<ucode>[\w]+)/$',set_password, name='set_password'),
    url(r'^user-login/$',user_login, name='user_login'),
    url(r'^user-logout/$',user_logout, name='user_logout'),
    url(r'^index/$',index, name='index'),
]

multidb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('m_db.urls', namespace='m_db')),
    url(r'^products/', include('products.urls', namespace='products')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url
from .views import add_product, show_all_products, edit_product, delete_product, admin_show_all_products


urlpatterns = [
    url(r'^add-product/$', add_product, name='add_product'),
    url(r'^edit-product/(?P<product_id>\d+)/(?P<database>\w+)$', edit_product, name='edit_product'),
    url(r'^delete-product/(?P<product_id>\d+)/(?P<database>\w+)$', delete_product, name='delete_product'),
    url(r'^show-all-products/$', show_all_products, name='show_all_products'),
    url(r'^admin-show-all-products/$', admin_show_all_products, name='admin_show_all_products')
]

products/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils.functional import cached_property

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=128)
    image = models.ImageField(upload_to='products/images', blank=True)
    price = models.IntegerField(default=0)
    user = models.IntegerField(default=None, null=True)

    def __unicode__(self):
        return self.name

    @cached_property
    def username(self):
    	return User.objects.get(id=self.user).username

products/forms.py
from django import forms
from django.contrib.auth.models import User
from m_db.models import UserDatabases
from django.conf import settings


from .models import Product



class ProductForm(forms.ModelForm):
	user_databases = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple)
	class Meta:
		model = Product
		fields = '__all__'

	def __init__(self, user, database=None, *args, **kwargs):
		super(ProductForm, self).__init__(*args, **kwargs)
		self.fields['user'].initial=user.id
		self.fields['user'].widget = forms.HiddenInput()
		try:
			if user.is_superuser:
				assigned_db = [(k, k) for k in settings.DATABASES.keys() if k != 'default']
			else:
				assigned_db = [(k, k) for k in settings.DATABASES.keys() if k in user.userdatabases.databases]
			
			self.fields['user_databases'].choices = assigned_db
			if database:
				self.fields['user_databases'].initial = [database]
				self.fields['user_databases'].widget = forms.MultipleHiddenInput()
		except UserDatabases.DoesNotExist:
			pass

products/views.py
from django.shortcuts import render, redirect, Http404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.conf import settings

from .models import Product
from .forms import ProductForm
from m_db.models import UserDatabases

# Create your views here.

@login_required
@user_passes_test(lambda u: u.is_superuser)
def admin_show_all_products(request, template_name='products_dashboard.html'):
	user = request.user
	all_products = {}
	databases =  [x for x in settings.DATABASES.keys() if x!='default']
	for each_db in databases:
		all_products[each_db] = Product.objects.using(each_db).all()
	context = {
		'all_products': all_products
	}
	return render(request, template_name, context)

@login_required
def show_all_products(request, template_name='products_dashboard.html'):
	user = request.user
	all_products = {}
	user_databases = user.userdatabases.databases
	for each_db in user_databases:
		all_products[each_db] = Product.objects.using(each_db).filter(user=user.id)
	context = {
		'all_products': all_products
	}
	return render(request, template_name, context)

@login_required
def add_product(request, template_name='add_update_product.html'):
	
	if request.method=='POST':
		add_product_form = ProductForm(request.user,None, request.POST, request.FILES)
		if add_product_form.is_valid():
			user_databases = add_product_form.cleaned_data.pop('user_databases')
			for each_db in user_databases:
				f = add_product_form.save(commit = False)
				f.save(using=each_db)
			if request.user.is_superuser:
				return redirect('products:admin_show_all_products')
			return redirect('products:show_all_products')
	else:
		add_product_form = ProductForm(request.user)

	context = {
		'form':add_product_form
	}

	return render(request, template_name, context)

@login_required
def edit_product(request, product_id, database, template_name='add_update_product.html'):
	try:
		if request.user.is_superuser:
			product = Product.objects.using(database).get(id=product_id)
		else:
			product = Product.objects.using(database).get(id=product_id, user=request.user.id)
	except Product.DoesNotExist:
		raise Http404

	if request.method=='POST':
		update_product_form = ProductForm(request.user, database, request.POST, request.FILES, instance=product)
		if update_product_form.is_valid():
			user_databases = update_product_form.cleaned_data.pop('user_databases')
			for each_db in user_databases:
				f = update_product_form.save(commit = False)
				f.save(using=each_db)
			if request.user.is_superuser:
				return redirect('products:admin_show_all_products')
			return redirect('products:show_all_products')
	else:
		update_product_form = ProductForm(request.user, database, instance=product)

	context = {
		'form':update_product_form,
		'is_update':True
	}
	return render(request, template_name, context)


@login_required
def delete_product(request, product_id, database):
	try:
		if request.user.is_superuser:
			product = Product.objects.using(database).get(id=product_id)
		else:
			product = Product.objects.using(database).get(id=product_id, user=request.user.id)
		product.delete()
		
		if request.user.is_superuser:
			return redirect('products:admin_show_all_products')
		return redirect('products:show_all_products')
	except Product.DoesNotExist:
		raise Http404

products/templates/add_update_product.html
{% extends 'base.html' %}

{% block css %}
	<style type="text/css">
		form{
			border: 1px solid gray;
			width: 300px;
			height: auto;
			padding: 10px;
			box-shadow: 1px 1px;
		}
	</style>
{% endblock %}

{% block content %}
	<div class="container">
	  <form method="post" enctype="multipart/form-data">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <button type="submit">{% if is_update %}Update{% else %}Add{% endif %} Product</button>
	  </form>
  </div>
{% endblock %}

products/templates/index.html
{% extends "base.html" %}

{% block content %}
	<div>
		Hi <strong>{{request.user.username}}</strong>
		<br>
		Welcome to Systengo Multidb
		<br>
		You have been assisgned the following databases
		<ul>
			{% for each_db in user_databases %}
			<li>{{each_db}}</li>
			{% endfor %}
		</ul>
	</div>
{% endblock %}

products/templates/products_dashboard.html
{% extends "base.html" %}

{% block css %}
<style type="text/css">
	.product{
		margin-left: 15px;
		padding: 10px;
		border: 1px solid darkblue;
		box-shadow: 1px 2px lightblue;
		width: 180px;
		float : left;
	}
	.edit-btn{
		margin-bottom: 5px;
	}
	.delete-btn{
		float: right;
		font-size: x-large;
		color: red;
	}
</style>
{% endblock %}

{% block content %}
<div class="container-fluid">
	{% for db, products in all_products.iteritems %}
		{% for each_product in products %}
			<div class="product">
				<a href="{% url 'products:edit_product' each_product.id db %}" class="btn btn-primary edit-btn">Edit</a>
				<a href="{% url 'products:delete_product' each_product.id db %}" class="delete-btn"><span aria-hidden="true">&times;</span></a>
				<img src="/media/{{each_product.image}}" style="height: 150px; width: 150px;">
				<br>
				<span>Name : {{each_product.name}}</span>
				<br>
				<span>Price : {{each_product.price}}</span>
				<br>
				<span>DB : {{db}}</span>
				{% if request.user.is_superuser %}
				<br>
				<span>User : {{each_product.username}}</span>
				{% endif %}
			</div>
		{% endfor %}
	{% endfor %}
</div>

{% endblock %}