m_db/urls.py
from django.conf.urls import url
from .views import set_password, user_login, user_logout, index


urlpatterns = [
    url(r'^set-password/(?P<ucode>[\w]+)/$',set_password, name='set_password'),
    url(r'^user-login/$',user_login, name='user_login'),
    url(r'^user-logout/$',user_logout, name='user_logout'),
    url(r'^index/$',index, name='index'),
]

multidb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('m_db.urls', namespace='m_db')),
    url(r'^products/', include('products.urls', namespace='products')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url
from .views import add_product, show_all_products, edit_product, delete_product, admin_show_all_products


urlpatterns = [
    url(r'^add-product/$', add_product, name='add_product'),
    url(r'^edit-product/(?P<product_id>\d+)/(?P<database>\w+)$', edit_product, name='edit_product'),
    url(r'^delete-product/(?P<product_id>\d+)/(?P<database>\w+)$', delete_product, name='delete_product'),
    url(r'^show-all-products/$', show_all_products, name='show_all_products'),
    url(r'^admin-show-all-products/$', admin_show_all_products, name='admin_show_all_products')
]

m_db/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField
from django.conf import settings

# Create your models here.

USER_DATABASES = [(k, k) for k in settings.DATABASES.keys() if k!='default']


class UserDatabases(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	databases = MultiSelectField(choices=USER_DATABASES)

	class Meta:
		verbose_name = 'User Databases'
		verbose_name_plural = 'Users Databases'


class ResetPassword(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	ucode = models.CharField(max_length=20, default=None)
	sent_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(null=True)

m_db/forms.py
from django import forms
from django.forms.models import BaseInlineFormSet
from django.contrib.auth.models import User

class UserRegistrationForm(forms.ModelForm):
	class Meta: 
		modal = User
		fields = ('first_name', 'last_name','email','username')

	def __init__(self, *args, **kwargs):

		#parent constructor
		super(UserRegistrationForm, self).__init__(*args, **kwargs)

		self.fields['email'].required=True

class UserDatabasesInlineForm(BaseInlineFormSet):

	def _construct_form(self, *args, **kwargs):
		"""
		Override the method to change the form attribute empty_permitted
		"""
		form = super(UserDatabasesInlineForm, self)._construct_form(*args, **kwargs)
		form.empty_permitted = False
		return form

m_db/views.py
from django.shortcuts import render, reverse,  get_object_or_404, redirect
from django.contrib.auth.forms import SetPasswordForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .models import ResetPassword, UserDatabases

# Create your views here.


def set_password(request, ucode, template_name='set_password.html'):
	obj = get_object_or_404(ResetPassword, ucode=ucode)
	user = obj.user
	if request.method=='POST':
		set_password_form = SetPasswordForm(user,request.POST)
		if set_password_form.is_valid():
			set_password_form.save()
			return redirect(reverse('m_db:user_login'))
	else:
		set_password_form = SetPasswordForm(user=user)

	context = {
		'form':set_password_form
	}

	return render(request,
		template_name,
		context
		)

def user_login(request, template_name='user_login.html'):
	if request.user.is_authenticated():
		return redirect(reverse('m_db:index'))
	if request.method == 'POST':
		login_form = AuthenticationForm(data=request.POST)
		if login_form.is_valid():
			login_details = login_form.cleaned_data
			user = authenticate(**login_details)
			if user:
				login(request, user)
				return redirect(reverse('m_db:index'))
			else:
				messages.error(request, "Invalid User")
	else:
		login_form = AuthenticationForm()

	context = {
		'form':login_form
	}
	return render(request,
		template_name,
		context
		)

@login_required
def index(request, template_name='index.html'):
	user = request.user
	try:
		user_databases = user.userdatabases.databases
	except UserDatabases.DoesNotExist:
		pass
	if request.user.is_superuser:
		user_databases = [k for k in settings.DATABASES.keys() if k!='default']
	else:
		user_databases = user.userdatabases.databases
	context = {
		'user_databases':user_databases
	}
	return render(request, template_name, context)

def user_logout(request):
	if request.user.is_authenticated():
		logout(request)
	
	return redirect(reverse('m_db:user_login'))

m_db/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Multidb</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  {% block css %}
  {% endblock %}

  {% block js %}
  {% endblock %}
</head>
<body>

<div class="container-fluid">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'm_db:index' %}">Systengo Multidb</a>
      </div>
      <ul class="nav navbar-nav">
        {% if request.user.is_authenticated %}
          {% if request.user.is_superuser %}
            <li class="active"><a href="{% url 'products:admin_show_all_products' %}">Show All Products</a></li>
          {% else %}
            <li class="active"><a href="{% url 'products:show_all_products' %}">Show Your Products</a></li>
          {% endif %}
          <li class="active"><a href="{% url 'products:add_product' %}">Add Product</a></li>
        {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if not request.user.is_authenticated %}
          <li><a href="{% url 'm_db:user_login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        {% else %}
          <li><a href="{% url 'm_db:user_logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        {% endif %}
        </ul>
    </div>
  </nav>
  {% block content %}
  {% endblock %}
</div>

</body>
</html>

m_db/templates/set_password.html
{% extends "base.html" %}

{% block css %}
<style type="text/css">
	form{
		margin: 10px;
	}
</style>
{% endblock %}

{% block content %}
<div class="container-fluid">
	<form method="POST">{% csrf_token %}
	{{form.as_p}}
	<button class="btn btn-default">submit</button>
	</form>
</div>

{% endblock %}

m_db/templates/user_login.html
{% extends "base.html" %}

{% block css %}
<style type="text/css">
	form{
		margin: 10px;
	}
	.errorlist li{
		color: red;
	}
</style>
{% endblock %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class="container-fluid">
	<form method="POST">{% csrf_token %}
	{{form.as_p}}
	<button class="btn btn-default">submit</button>
	</form>
</div>

{% endblock %}

m_db/templates/user_registration_email.html
Hi {{username}},
Your account has been created on Systengo Multidb.
username : {{username}}
to access it please <a href="{{set_password_link}}">click here</a> reset the password.

Thanks
Systengo Test Team.